#ifndef __TOUCH_APP_H
#define __TOUCH_APP_H

#define TOUCH_BUTTON_PLAY     TOUCH_PAD_NUM2
#define TOUCH_BUTTON_PHOTO    TOUCH_PAD_NUM6
#define TOUCH_BUTTON_NETWORK  TOUCH_PAD_NUM11
#define TOUCH_BUTTON_RECORD   TOUCH_PAD_NUM5
#define TOUCH_BUTTON_VOLUP    TOUCH_PAD_NUM1
#define TOUCH_BUTTON_VOLDOWN  TOUCH_PAD_NUM3
#define TOUCH_BUTTON_GUARD    TOUCH_PAD_NUM4
#define TOUCH_SHELED_ELECT    TOUCH_PAD_NUM14

#define CONFIG_EXAMPLE_RMT_TX_GPIO 45
#define CONFIG_EXAMPLE_STRIP_LED_NUMBER 1


void touch_app_init(void);

#endif